apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agrosolutions

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-identity.yaml
  - postgres-property.yaml
  - postgres-ingestion.yaml
  - postgres-alerts.yaml
  - rabbitmq.yaml
  - identity-api.yaml
  - property-api.yaml
  - ingestion-api.yaml
  - alerts-api.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: agrosolutions
  app.kubernetes.io/part-of: agrosolutions-platform